
package br.com.correiows.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CorreiosWSService", targetNamespace = "http://ws.correios.uscs.edu.br/", wsdlLocation = "http://localhost:8080/correios-ws/CorreiosWS?wsdl")
public class CorreiosWSService
    extends Service
{

    private final static URL CORREIOSWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CORREIOSWSSERVICE_EXCEPTION;
    private final static QName CORREIOSWSSERVICE_QNAME = new QName("http://ws.correios.uscs.edu.br/", "CorreiosWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/correios-ws/CorreiosWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CORREIOSWSSERVICE_WSDL_LOCATION = url;
        CORREIOSWSSERVICE_EXCEPTION = e;
    }

    public CorreiosWSService() {
        super(__getWsdlLocation(), CORREIOSWSSERVICE_QNAME);
    }

    public CorreiosWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CORREIOSWSSERVICE_QNAME, features);
    }

    public CorreiosWSService(URL wsdlLocation) {
        super(wsdlLocation, CORREIOSWSSERVICE_QNAME);
    }

    public CorreiosWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CORREIOSWSSERVICE_QNAME, features);
    }

    public CorreiosWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CorreiosWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CorreiosWS
     */
    @WebEndpoint(name = "CorreiosWSPort")
    public CorreiosWS getCorreiosWSPort() {
        return super.getPort(new QName("http://ws.correios.uscs.edu.br/", "CorreiosWSPort"), CorreiosWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CorreiosWS
     */
    @WebEndpoint(name = "CorreiosWSPort")
    public CorreiosWS getCorreiosWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.correios.uscs.edu.br/", "CorreiosWSPort"), CorreiosWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CORREIOSWSSERVICE_EXCEPTION!= null) {
            throw CORREIOSWSSERVICE_EXCEPTION;
        }
        return CORREIOSWSSERVICE_WSDL_LOCATION;
    }

}
