
package br.com.correiows.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CorreiosWS", targetNamespace = "http://ws.correios.uscs.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CorreiosWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.correiows.client.Endereco
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarEndereco", targetNamespace = "http://ws.correios.uscs.edu.br/", className = "br.com.correiows.client.ConsultarEndereco")
    @ResponseWrapper(localName = "consultarEnderecoResponse", targetNamespace = "http://ws.correios.uscs.edu.br/", className = "br.com.correiows.client.ConsultarEnderecoResponse")
    public Endereco consultarEndereco(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
