
package br.com.correiows.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CorreiosWS", targetNamespace = "http://ws.correios.uscs.edu.br/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CorreiosWS {


    /**
     * 
     * @param parameters
     * @return
     *     returns br.com.correiows.client.ConsultarEnderecoResponse
     */
    @WebMethod
    @WebResult(name = "consultarEnderecoResponse", targetNamespace = "http://ws.correios.uscs.edu.br/", partName = "parameters")
    public ConsultarEnderecoResponse consultarEndereco(
        @WebParam(name = "consultarEndereco", targetNamespace = "http://ws.correios.uscs.edu.br/", partName = "parameters")
        ConsultarEndereco parameters);

}
