package br.edu.uscs.correios.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-07-15T21:25:24.688-03:00
 * Generated source version: 3.1.1
 * 
 */
@WebServiceClient(name = "CorreiosWSService", 
                  wsdlLocation = "http://localhost:8080/correios-ws/CorreiosWS?wsdl",
                  targetNamespace = "http://ws.correios.uscs.edu.br/") 
public class CorreiosWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.correios.uscs.edu.br/", "CorreiosWSService");
    public final static QName CorreiosWSPort = new QName("http://ws.correios.uscs.edu.br/", "CorreiosWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/correios-ws/CorreiosWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CorreiosWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/correios-ws/CorreiosWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CorreiosWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CorreiosWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CorreiosWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CorreiosWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CorreiosWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CorreiosWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CorreiosWS
     */
    @WebEndpoint(name = "CorreiosWSPort")
    public CorreiosWS getCorreiosWSPort() {
        return super.getPort(CorreiosWSPort, CorreiosWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CorreiosWS
     */
    @WebEndpoint(name = "CorreiosWSPort")
    public CorreiosWS getCorreiosWSPort(WebServiceFeature... features) {
        return super.getPort(CorreiosWSPort, CorreiosWS.class, features);
    }

}
